apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-ks-test
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/vterdunov/flux-ks-test.git
